-   repo: https://github.com/pycqa/flake8
    rev: ''  # pick a git hash / tag to point to
    hooks:
    - id: flake8
      args: ['--config=.flake8']
      additional_dependencies: [ flake8-docstrings ]
